dllmain.cpp
GLFWwindow* window
Referenced by __declspec.
const uint16_t Win_W
Referenced by __declspec, bx, ColorData, ContTransformData, DrawRasterLinesX, DrawStripesX, FirstPassTransformData, fx, GenerateRaster, px, ux.
const uint16_t Win_H
Referenced by __declspec, DrawRasterLinesY, DrawStripesY, fy, GenerateRaster, py, uy.
GLfloat g_vertex_buffer_raster[3004][3004]
Referenced by __declspec, DrawRasterLinesX, DrawRasterLinesY, DrawStripesX, DrawStripesY.
GLfloat g_color_buffer_raster[4506][4506]
Referenced by __declspec, DrawRasterLinesX, DrawRasterLinesY, DrawStripesX, DrawStripesY.
GLfloat g_vertex_buffer_data[(Win_W+4)*6][(Win_W+4)*6]
Referenced by __declspec, ContTransformData, FirstPassTransformData.
GLfloat g_color_buffer_data[(Win_W+4)*9][(Win_W+4)*9]
Referenced by __declspec, ColorData.
GLushort g_indices[(Win_W+4)*4][(Win_W+4)*4]
Referenced by __declspec, FirstPassTransformData.
uint16_t ADC_res
Referenced by ContTransformData, FirstPassTransformData, Reading::gVolt_LowerBound, Reading::gVolt_UpperBound.
uint16_t ADC_Vref
Referenced by ContTransformData, FirstPassTransformData, Reading::gVolt.
uint16_t zeroVolt
Referenced by ContTransformData, FirstPassTransformData.
uint16_t VoltDiv
Referenced by ContTransformData, FirstPassTransformData.
float TimeDiv
Referenced by ContTransformData, FirstPassTransformData.
uint16_t TScale
Referenced by ContTransformData, FirstPassTransformData, Reading::gfTScreenFromTick.
uint32_t ADC_freq
Referenced by ContTransformData, FirstPassTransformData.
uint16_t VScale
Referenced by ContTransformData.
const uint32_t RB_Size
Referenced by ContCollectData, ContTransformData, FirstPassCollectData, FirstPassTransformData.
uint32_t RB_U
Referenced by ContCollectData, ContTransformData.
uint32_t RB_L
Referenced by ContCollectData, ContTransformData.
uint32_t NumberOfSamples
Referenced by ContCollectData.
uint16_t BD_U
Referenced by ContTransformData.
uint16_t BD_L
Referenced by ContTransformData.
int32_t counter
Referenced by ContCollectData, FirstPassCollectData.
Reading* Samples
Referenced by __declspec, ContCollectData, ContTransformData, FirstPassCollectData, FirstPassTransformData.
int ThreadNr
Referenced by ContCollecData.
float dfx
Referenced by ContTransformData.
float Bound
Referenced by ContTransformData.
float Sample
uint16_t NumberOfPixels
Referenced by ContTransformData.
BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)
float fx(uint16_t px)
References Win_W.
Referenced by DrawRasterLinesX, DrawRasterLinesY, DrawStripesX, DrawStripesY, FirstPassTransformData.
float fy(uint16_t py)
References Win_H.
Referenced by DrawRasterLinesX, DrawRasterLinesY, DrawStripesX, DrawStripesY.
uint16_t px(float fx)
References Win_W.
Referenced by FirstPassTransformData.
uint16_t py(float fy)
References Win_H.
uint16_t ux(uint16_t u)
References Win_W.
Referenced by DrawStripesX, DrawStripesY, GenerateRaster.
uint16_t uy(uint16_t u)
References Win_H.
Referenced by DrawStripesX, DrawStripesY, GenerateRaster.
uint16_t bx(uint16_t px0, uint16_t dx)
References Win_W.
void DrawRasterLinesX(unsigned int y, int *a, int *b)
References fx, fy, g_color_buffer_raster, g_vertex_buffer_raster, Win_W.
Referenced by GenerateRaster.
void DrawRasterLinesY(unsigned int x, int *a, int *b)
References fx, fy, g_color_buffer_raster, g_vertex_buffer_raster, Win_H.
Referenced by GenerateRaster.
void DrawStripesX(unsigned int y1, int *a, int *b)
References fx, fy, g_color_buffer_raster, g_vertex_buffer_raster, ux, uy, Win_W.
Referenced by GenerateRaster.
void DrawStripesY(unsigned int x1, int *a, int *b)
References fx, fy, g_color_buffer_raster, g_vertex_buffer_raster, ux, uy, Win_H.
Referenced by GenerateRaster.
void GenerateRaster(void)
References DrawRasterLinesX, DrawRasterLinesY, DrawStripesX, DrawStripesY, ux, uy, Win_H, Win_W.
Referenced by __declspec.
void breaktest(void)
void FirstPassCollectData(void)
References Reading::ADC_Reading, Reading::ADC_Tick, counter, RB_Size, Samples.
Referenced by __declspec.
void FirstPassTransformData(void)
References ADC_freq, ADC_res, ADC_Vref, fx, g_indices, g_vertex_buffer_data, Reading::gfVScreen, px, RB_Size, Samples, TimeDiv, TScale, VoltDiv, Win_W, zeroVolt.
Referenced by __declspec.
void ColorData(void)
References g_color_buffer_data, Win_W.
Referenced by __declspec.
uint32_t r(int32_t Number, int32_t UBound, int32_t LBound)
Referenced by ContCollectData, ContTransformData.
uint32_t Im(uint32_t Number, uint32_t RefNumber, uint32_t UBound, uint32_t LBound)
Referenced by ContCollectData.
void ContCollectData(void)
References Reading::ADC_Reading, Reading::ADC_Tick, counter, Im, NumberOfSamples, r, RB_L, RB_Size, RB_U, Samples.
Referenced by __declspec.
void getUSBdata(void *MyID)
Referenced by ContCollecData.
void ContCollecData(void)
References getUSBdata, ThreadNr.
void ContTransformData(void)
References ADC_freq, Reading::ADC_Reading, ADC_res, Reading::ADC_Tick, ADC_Vref, BD_L, BD_U, Bound, dfx, g_vertex_buffer_data, Reading::gTime, NumberOfPixels, r, RB_L, RB_Size, RB_U, Samples, TimeDiv, TScale, VoltDiv, VScale, Win_W, zeroVolt.
Referenced by __declspec.
__declspec(dllexport) void OGL_Window_Init()
References ColorData, ContCollectData, ContTransformData, FirstPassCollectData, FirstPassTransformData, g_color_buffer_data, g_color_buffer_raster, g_indices, g_vertex_buffer_data, g_vertex_buffer_raster, GenerateRaster, glfwSetWindowPos, LoadShaders, Samples, Win_H, Win_W, window.
int y glfwSetWindowPos(window, x, y)
Referenced by __declspec.