Osc_v5::Form1
Label [] Osc_v5.Form1.Lbl_V_Axis
Referenced by Osc_v5.Form1.U_InitializeComponent.
Label [] Osc_v5.Form1.Lbl_T_Axis
Number [] Osc_v5.Form1.V_axis
Referenced by Osc_v5.Form1.comboBox1_SelectedValueChanged.
Number [] Osc_v5.Form1.T_axis
Referenced by Osc_v5.Form1.comboBox2_SelectedValueChanged.
Number Osc_v5.Form1.zeroVoltPoint
Number Osc_v5.Form1.VoltDiv
Number Osc_v5.Form1.TimeDiv
System.ComponentModel.IContainer Osc_v5.Form1.components
Referenced by Osc_v5.Form1.Dispose.
Button Osc_v5.Form1.button2
TrackBar Osc_v5.Form1.trackBar1
Referenced by Osc_v5.Form1.InitializeComponent.
Panel Osc_v5.Form1.panel1
Panel Osc_v5.Form1.panel2
Button Osc_v5.Form1.button6
Button Osc_v5.Form1.button7
Button Osc_v5.Form1.button5
ComboBox Osc_v5.Form1.comboBox1
TextBox Osc_v5.Form1.textBox1
Referenced by Osc_v5.Form1.textBox1_KeyPress.
ComboBox Osc_v5.Form1.comboBox2
Osc_v5.Form1.Form1()
References Osc_v5.Form1.Form1_Move, Osc_v5.Form1.Form1_Shown, Osc_v5.Form1.InitializeComponent, Osc_v5.Form1.U_InitializeComponent.
void Osc_v5.Form1.Form1_Move(Object sender, EventArgs e)
Referenced by Osc_v5.Form1.Form1.
void Osc_v5.Form1.button6_Click(object sender, EventArgs e)
void Osc_v5.Form1.Form1_Shown(object sender, EventArgs e)
Referenced by Osc_v5.Form1.Form1.
void Osc_v5.Form1.MidLbl_Click(object sender, EventArgs e)
void Osc_v5.Form1.button7_Click(object sender, EventArgs e)
void Osc_v5.Form1.button5_Click(object sender, EventArgs e)
void Osc_v5.Form1.textBox1_KeyPress(object sender, KeyPressEventArgs e)
References Osc_v5.Form1.textBox1.
void Osc_v5.Form1.textBox1_PreviewKeyDown(object sender, PreviewKeyDownEventArgs e)
void Osc_v5.Form1.comboBox1_SelectedValueChanged(object sender, EventArgs e)
References Osc_v5.Form1.V_axis.
void Osc_v5.Form1.comboBox2_SelectedValueChanged(object sender, EventArgs e)
References Osc_v5.Form1.T_axis.
void Osc_v5.Form1.U_InitializeComponent()
References Osc_v5.Form1.Lbl_V_Axis.
Referenced by Osc_v5.Form1.Form1.
void Osc_v5.Form1.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References Osc_v5.Form1.trackBar1.
Referenced by Osc_v5.Form1.Form1.
override void Osc_v5.Form1.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References Osc_v5.Form1.components.